name: PHP CI

# Trigger workflow saat ada push atau pull request ke branch main dan develop.
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Ambil kode dari repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup PHP, pastikan versi sesuai yang kamu butuhkan dan tambahkan ekstensi jika diperlukan.
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          # daftar ekstensi PHP yang ingin diaktifkan
          extensions: mbstring, intl, pdo_mysql
          # mengatur nilai php.ini jika butuh
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: xdebug

      # Optional: Cache dependensi Composer untuk mempercepat builds di workflow berikutnya.
      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install dependensi project menggunakan Composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Jalankan testing menggunakan PHPUnit
      - name: Run Tests
        run: vendor/bin/phpunit --coverage-text --colors=never
