name: PHP CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=300

      # Jika kamu menggunakan Composer, pastikan file composer.json ada di root.
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Jika belum ada test, kamu bisa menghapus atau mengomentari langkah ini.
      # - name: Run Tests
      #   run: vendor/bin/phpunit --coverage-text --colors=never

      # Contoh tambahan: Melakukan pengecekan sintaks PHP di seluruh file
      - name: Cek Syntax PHP
        run: find . -name "*.php" -exec php -l {} \;
