name: PHP CI

# Trigger workflow saat ada push atau pull request ke branch main dan develop.
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Langkah 2: Setup PHP dengan versi yang diinginkan
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=300

      # Langkah 3: Install Dependencies via Composer
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      # Opsional: Tambahkan langkah lain sesuai kebutuhan,
      # misalnya menjalankan build script, CLI command, dll.
      # Jika di project kamu tidak ada langkah testing, tidak usah menambahkan step Run Tests.
